<a href="https://colab.research.google.com/github/SabrinAkter26nov/Sabrin-/blob/main/cse_assignment_1(2022333562).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/89cement data  (1).csv")

In [4]:
df.head()

,Month,Production,Sales,demand,population,gdp,disbusment,interestrate,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Jan-10,347.0,322.0,346.0,122.4,182277.0,60314.00,10.25,NaN,NaN,NaN,NaN,NaN,NaN
1,Feb-10,306.0,285.0,338.0,122.5,181018.0,61213.92,10.33,NaN,NaN,NaN,NaN,NaN,NaN
2,Mar-10,236.0,245.0,276.0,122.6,179759.0,62113.83,10.42,NaN,NaN,NaN,NaN,NaN,NaN
3,Apr-10,234.0,212.0,245.0,122.8,178500.0,63013.75,10.50,NaN,NaN,NaN,NaN,NaN,NaN
4,May-10,296.0,289.0,312.0,122.9,177354.0,63913.67,10.58,NaN,NaN,NaN,NaN,NaN,NaN